title: Ryan Pereira
name: Ryan Pereira
email: pereiraryan.rp@gmail.com
description: Software Engineer , graduated with a bachelor’s degree in Computer Engineering in 2016 from University of Mumbai . I am having around 2 year of professional experience in IT industry. My career objective is to obtain a meaningful and challenging position that enables me to learn new technologies and enables growth.

remote_theme: jameshamann/jekyll-material-theme

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

# Settings for the porfolio section

portfolio_heading: Portfolio
portfolio_type: cards #cards or carousel

project_one: Wireless Intrusion Prevention System
project_one_description: The primary purpose of the project is to prevent unauthorized network access to local area networks and other information assets by wireless devices. Scapy , a network packet manipulation library in Python is used to craft a Deauth packet; Tkinter for GUI design; Sqlite3 for database.
project_one_url: https://github.com/pereiraryan/WIPS
project_one_icon: location_on # these are from materiailize css, the full collection is here: http://materializecss.com/icons.html

project_two: My First Node Application
project_two_description: A node.js application build using mean stack.
project_two_url: https://github.com/pereiraryan/domains
project_two_icon: photo_camera


project_three: myConsole
project_three_description: A JavaScript editor for you phone, in JavaScript.
project_three_url: https://pereiraryan.github.io/myConsole/
project_three_icon: hotel


project_four: My Personal Blog
project_four_description: This blog is created with an intention to share my thoughts and experiences on new products and other entertainments.hope to have a awesome time.
project_four_url: https://pereiraryan.wordpress.com
project_four_icon: restaurant

project_five: Professional websites
project_five_description: This blog is created with an intention to share my thoughts and experiences on new products and other entertainments.hope to have a awesome time.
project_five_url: https://www.logicboxes.com
project_five_icon: photo_camera

# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: amazonwebservices
  - name: android
  - name: angularjs
  - name: apache
  - name: appcelerator
  - name: apple
  - name: atom
  - name: babel
  - name: backbonejs
  - name: bitbucket
  - name: bootstrap
  - name: bower
  - name: c
  - name: chrome
  - name: codeigniter
  - name: coffescript
  - name: confluence
  - name: cplusplus
  - name: csharp
  - name: css3
  - name: cucumber
  - name: d3js
  - name: debian
  - name: devicon
  - name: django
  - name: docker
  - name: doctrine
  - name: dot-net
  - name: drupal
  - name: erlang
  - name: facebook
  - name: firefox
  - name: foundation
  - name: gatling
  - name: gimp
  - name: git
  - name: github
  - name: gitlab
  - name: go
  - name: google
  - name: gradle
  - name: grunt
  - name: gulp
  - name: heroku
  - name: html5
  - name: ie10
  - name: illustrator
  - name: inkscape
  - name: itellij
  - name: java
  - name: jasmine
  - name: javascript
  - name: laravel
  - name: less
  - name: linux
  - name: meteor
  - name: mocha
  - name: mongodb
  - name: moodle
  - name: mysql
  - name: nginx
  - name: nodejs
  - name: nodewebkit
  - name: oracle
  - name: photoshop
  - name: php
  - name: phpstorm
  - name: protractor
  - name: postgresql
  - name: python
  - name: pycharm
  - name: rails
  - name: react
  - name: redhat
  - name: redis
  - name: ruby
  - name: rubymine
  - name: safari
  - name: sass
  - name: sequelize
  - name: slack
  - name: sourcetree
  - name: ssh
  - name: swift
  - name: symfony
  - name: tomcat
  - name: travis
  - name: trello
  - name: twitter
  - name: typescript
  - name: ubuntu
  - name: vim
  - name: visualstudio
  - name: vuejs
  - name: webpack
  - name: webstorm
  - name: windows8
  - name: wordpress
  - name: yii
  - name: zend

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/pereiraryan
medium: https://medium.com/@ryanpereira_94708

baseurl: # If your site is located at /blog or /home, change it here, otherwise leave it empty
url: http://localhost:4000/ # The URL of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: GTM-KJBQS3Q # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: UA-115151000-1 # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookie_accept_message: Thanks! # The pop-up dialog that appears after accepting the cookie notice.

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
